services:
  - type: web
    name: bhutanese-textile-detector
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn backend.app:app
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
